/*NORMAL*/
insert into Effectiveness values("NORMAL", "NORMAL", 1);
insert into Effectiveness values("NORMAL", "FIRE", 1);
insert into Effectiveness values("NORMAL", "WATER", 1);
insert into Effectiveness values("NORMAL", "ELECTRIC", 1);
insert into Effectiveness values("NORMAL", "GRASS", 1);
insert into Effectiveness values("NORMAL", "ICE", 1);
insert into Effectiveness values("NORMAL", "FIGHTING", 1);
insert into Effectiveness values("NORMAL", "POISON", 1);
insert into Effectiveness values("NORMAL", "GROUND", 1);
insert into Effectiveness values("NORMAL", "FLYING", 1);
insert into Effectiveness values("NORMAL", "PSYCHIC", 1);
insert into Effectiveness values("NORMAL", "BUG", 1);
insert into Effectiveness values("NORMAL", "ROCK", 0.5);
insert into Effectiveness values("NORMAL", "GHOST", 0);
insert into Effectiveness values("NORMAL", "DRAGON", 1);
insert into Effectiveness values("NORMAL", "DARK", 1);
insert into Effectiveness values("NORMAL", "STEEL", 0.5);
insert into Effectiveness values("NORMAL", "FAIRY", 1);

/*FIRE*/
insert into Effectiveness values("FIRE", "NORMAL", 1);
insert into Effectiveness values("FIRE", "FIRE", 0.5);
insert into Effectiveness values("FIRE", "WATER", 0.5);
insert into Effectiveness values("FIRE", "ELECTRIC", 1);
insert into Effectiveness values("FIRE", "GRASS", 2);
insert into Effectiveness values("FIRE", "ICE", 2);
insert into Effectiveness values("FIRE", "FIGHTING", 1);
insert into Effectiveness values("FIRE", "POISON", 1);
insert into Effectiveness values("FIRE", "GROUND", 1);
insert into Effectiveness values("FIRE", "FLYING", 1);
insert into Effectiveness values("FIRE", "PSYCHIC", 1);
insert into Effectiveness values("FIRE", "BUG", 2);
insert into Effectiveness values("FIRE", "ROCK", 0.5);
insert into Effectiveness values("FIRE", "GHOST", 1);
insert into Effectiveness values("FIRE", "DRAGON", 0.5);
insert into Effectiveness values("FIRE", "DARK", 1);
insert into Effectiveness values("FIRE", "STEEL", 2);
insert into Effectiveness values("FIRE", "FAIRY", 1);

/*WATER*/
insert into Effectiveness values("WATER", "NORMAL", 1);
insert into Effectiveness values("WATER", "FIRE", 2);
insert into Effectiveness values("WATER", "WATER", 0.5);
insert into Effectiveness values("WATER", "ELECTRIC", 1);
insert into Effectiveness values("WATER", "GRASS", 0.5);
insert into Effectiveness values("WATER", "ICE", 1);
insert into Effectiveness values("WATER", "FIGHTING", 1);
insert into Effectiveness values("WATER", "POISON", 1);
insert into Effectiveness values("WATER", "GROUND", 2);
insert into Effectiveness values("WATER", "FLYING", 1);
insert into Effectiveness values("WATER", "PSYCHIC", 1);
insert into Effectiveness values("WATER", "BUG", 1);
insert into Effectiveness values("WATER", "ROCK", 2);
insert into Effectiveness values("WATER", "GHOST", 1);
insert into Effectiveness values("WATER", "DRAGON", 0.5);
insert into Effectiveness values("WATER", "DARK", 1);
insert into Effectiveness values("WATER", "STEEL", 1);
insert into Effectiveness values("WATER", "FAIRY", 1);

/*ELECTRIC*/
insert into Effectiveness values("ELECTRIC", "NORMAL", 1);
insert into Effectiveness values("ELECTRIC", "FIRE", 1);
insert into Effectiveness values("ELECTRIC", "WATER", 2);
insert into Effectiveness values("ELECTRIC", "ELECTRIC", 0.5);
insert into Effectiveness values("ELECTRIC", "GRASS", 0.5);
insert into Effectiveness values("ELECTRIC", "ICE", 1);
insert into Effectiveness values("ELECTRIC", "FIGHTING", 1);
insert into Effectiveness values("ELECTRIC", "POISON", 1);
insert into Effectiveness values("ELECTRIC", "GROUND", 0);
insert into Effectiveness values("ELECTRIC", "FLYING", 2);
insert into Effectiveness values("ELECTRIC", "PSYCHIC", 1);
insert into Effectiveness values("ELECTRIC", "BUG", 1);
insert into Effectiveness values("ELECTRIC", "ROCK", 1);
insert into Effectiveness values("ELECTRIC", "GHOST", 1);
insert into Effectiveness values("ELECTRIC", "DRAGON", 0.5);
insert into Effectiveness values("ELECTRIC", "DARK", 1);
insert into Effectiveness values("ELECTRIC", "STEEL", 1);
insert into Effectiveness values("ELECTRIC", "FAIRY", 1);

/*GRASS*/
insert into Effectiveness values("GRASS", "NORMAL", 1);
insert into Effectiveness values("GRASS", "FIRE", 0.5);
insert into Effectiveness values("GRASS", "WATER", 2);
insert into Effectiveness values("GRASS", "ELECTRIC", 1);
insert into Effectiveness values("GRASS", "GRASS", 0.5);
insert into Effectiveness values("GRASS", "ICE", 1);
insert into Effectiveness values("GRASS", "FIGHTING", 1);
insert into Effectiveness values("GRASS", "POISON", 0.5);
insert into Effectiveness values("GRASS", "GROUND", 2);
insert into Effectiveness values("GRASS", "FLYING", 0.5);
insert into Effectiveness values("GRASS", "PSYCHIC", 1);
insert into Effectiveness values("GRASS", "BUG", 0.5);
insert into Effectiveness values("GRASS", "ROCK", 2);
insert into Effectiveness values("GRASS", "GHOST", 1);
insert into Effectiveness values("GRASS", "DRAGON", 0.5);
insert into Effectiveness values("GRASS", "DARK", 1);
insert into Effectiveness values("GRASS", "STEEL", 0.5);
insert into Effectiveness values("GRASS", "FAIRY", 1);

/*ICE*/
insert into Effectiveness values("ICE", "NORMAL", 1);
insert into Effectiveness values("ICE", "FIRE", 0.5);
insert into Effectiveness values("ICE", "WATER", 0.5);
insert into Effectiveness values("ICE", "ELECTRIC", 1);
insert into Effectiveness values("ICE", "GRASS", 2);
insert into Effectiveness values("ICE", "ICE", 0.5);
insert into Effectiveness values("ICE", "FIGHTING", 1);
insert into Effectiveness values("ICE", "POISON", 1);
insert into Effectiveness values("ICE", "GROUND", 2);
insert into Effectiveness values("ICE", "FLYING", 2);
insert into Effectiveness values("ICE", "PSYCHIC", 1);
insert into Effectiveness values("ICE", "BUG", 1);
insert into Effectiveness values("ICE", "ROCK", 1);
insert into Effectiveness values("ICE", "GHOST", 1);
insert into Effectiveness values("ICE", "DRAGON", 2);
insert into Effectiveness values("ICE", "DARK", 1);
insert into Effectiveness values("ICE", "STEEL", 0.5);
insert into Effectiveness values("ICE", "FAIRY", 1);

/*FIGHTING*/
insert into Effectiveness values("FIGHTING", "NORMAL", 2);
insert into Effectiveness values("FIGHTING", "FIRE", 1);
insert into Effectiveness values("FIGHTING", "WATER", 1);
insert into Effectiveness values("FIGHTING", "ELECTRIC", 1);
insert into Effectiveness values("FIGHTING", "GRASS", 1);
insert into Effectiveness values("FIGHTING", "ICE", 2);
insert into Effectiveness values("FIGHTING", "FIGHTING", 1);
insert into Effectiveness values("FIGHTING", "POISON", 0.5);
insert into Effectiveness values("FIGHTING", "GROUND", 1);
insert into Effectiveness values("FIGHTING", "FLYING", 0.5);
insert into Effectiveness values("FIGHTING", "PSYCHIC", 0.5);
insert into Effectiveness values("FIGHTING", "BUG", 0.5);
insert into Effectiveness values("FIGHTING", "ROCK", 2);
insert into Effectiveness values("FIGHTING", "GHOST", 0);
insert into Effectiveness values("FIGHTING", "DRAGON", 1);
insert into Effectiveness values("FIGHTING", "DARK", 2);
insert into Effectiveness values("FIGHTING", "STEEL", 2);
insert into Effectiveness values("FIGHTING", "FAIRY", 0.5);

/*POISON*/
insert into Effectiveness values("POISON", "NORMAL", 1);
insert into Effectiveness values("POISON", "FIRE", 1);
insert into Effectiveness values("POISON", "WATER", 1);
insert into Effectiveness values("POISON", "ELECTRIC", 1);
insert into Effectiveness values("POISON", "GRASS", 2);
insert into Effectiveness values("POISON", "ICE", 1);
insert into Effectiveness values("POISON", "FIGHTING", 1);
insert into Effectiveness values("POISON", "POISON", 0.5);
insert into Effectiveness values("POISON", "GROUND", 0.5);
insert into Effectiveness values("POISON", "FLYING", 1);
insert into Effectiveness values("POISON", "PSYCHIC", 1);
insert into Effectiveness values("POISON", "BUG", 1);
insert into Effectiveness values("POISON", "ROCK", 0.5);
insert into Effectiveness values("POISON", "GHOST", 0.5);
insert into Effectiveness values("POISON", "DRAGON", 1);
insert into Effectiveness values("POISON", "DARK", 1);
insert into Effectiveness values("POISON", "STEEL", 0);
insert into Effectiveness values("POISON", "FAIRY", 2);

/*GROUND*/
insert into Effectiveness values("GROUND", "NORMAL", 1);
insert into Effectiveness values("GROUND", "FIRE", 2);
insert into Effectiveness values("GROUND", "WATER", 1);
insert into Effectiveness values("GROUND", "ELECTRIC", 2);
insert into Effectiveness values("GROUND", "GRASS", 0.5);
insert into Effectiveness values("GROUND", "ICE", 1);
insert into Effectiveness values("GROUND", "FIGHTING", 1);
insert into Effectiveness values("GROUND", "POISON", 2);
insert into Effectiveness values("GROUND", "GROUND", 1);
insert into Effectiveness values("GROUND", "FLYING", 0);
insert into Effectiveness values("GROUND", "PSYCHIC", 1);
insert into Effectiveness values("GROUND", "BUG", 0.5);
insert into Effectiveness values("GROUND", "ROCK", 2);
insert into Effectiveness values("GROUND", "GHOST", 1);
insert into Effectiveness values("GROUND", "DRAGON", 1);
insert into Effectiveness values("GROUND", "DARK", 1);
insert into Effectiveness values("GROUND", "STEEL", 2);
insert into Effectiveness values("GROUND", "FAIRY", 1);

/*FLYING*/
insert into Effectiveness values("FLYING", "NORMAL", 1);
insert into Effectiveness values("FLYING", "FIRE", 1);
insert into Effectiveness values("FLYING", "WATER", 1);
insert into Effectiveness values("FLYING", "ELECTRIC", 0.5);
insert into Effectiveness values("FLYING", "GRASS", 2);
insert into Effectiveness values("FLYING", "ICE", 1);
insert into Effectiveness values("FLYING", "FIGHTING", 2);
insert into Effectiveness values("FLYING", "POISON", 1);
insert into Effectiveness values("FLYING", "GROUND", 1);
insert into Effectiveness values("FLYING", "FLYING", 1);
insert into Effectiveness values("FLYING", "PSYCHIC", 1);
insert into Effectiveness values("FLYING", "BUG", 2);
insert into Effectiveness values("FLYING", "ROCK", 0.5);
insert into Effectiveness values("FLYING", "GHOST", 1);
insert into Effectiveness values("FLYING", "DRAGON", 1);
insert into Effectiveness values("FLYING", "DARK", 1);
insert into Effectiveness values("FLYING", "STEEL", 0.5);
insert into Effectiveness values("FLYING", "FAIRY", 1);

/*PSYCHIC*/
insert into Effectiveness values("PSYCHIC", "NORMAL", 1);
insert into Effectiveness values("PSYCHIC", "FIRE", 1);
insert into Effectiveness values("PSYCHIC", "WATER", 1);
insert into Effectiveness values("PSYCHIC", "ELECTRIC", 1);
insert into Effectiveness values("PSYCHIC", "GRASS", 1);
insert into Effectiveness values("PSYCHIC", "ICE", 1);
insert into Effectiveness values("PSYCHIC", "FIGHTING", 2);
insert into Effectiveness values("PSYCHIC", "POISON", 2);
insert into Effectiveness values("PSYCHIC", "GROUND", 1);
insert into Effectiveness values("PSYCHIC", "FLYING", 1);
insert into Effectiveness values("PSYCHIC", "PSYCHIC", 0.5);
insert into Effectiveness values("PSYCHIC", "BUG", 1);
insert into Effectiveness values("PSYCHIC", "ROCK", 1);
insert into Effectiveness values("PSYCHIC", "GHOST", 1);
insert into Effectiveness values("PSYCHIC", "DRAGON", 1);
insert into Effectiveness values("PSYCHIC", "DARK", 0);
insert into Effectiveness values("PSYCHIC", "STEEL", 0.5);
insert into Effectiveness values("PSYCHIC", "FAIRY", 1);

/*BUG*/
insert into Effectiveness values("BUG", "NORMAL", 1);
insert into Effectiveness values("BUG", "FIRE", 0.5);
insert into Effectiveness values("BUG", "WATER", 1);
insert into Effectiveness values("BUG", "ELECTRIC", 1);
insert into Effectiveness values("BUG", "GRASS", 2);
insert into Effectiveness values("BUG", "ICE", 1);
insert into Effectiveness values("BUG", "FIGHTING", 0.5);
insert into Effectiveness values("BUG", "POISON", 0.5);
insert into Effectiveness values("BUG", "GROUND", 1);
insert into Effectiveness values("BUG", "FLYING", 0.5);
insert into Effectiveness values("BUG", "PSYCHIC", 2);
insert into Effectiveness values("BUG", "BUG", 1);
insert into Effectiveness values("BUG", "ROCK", 1);
insert into Effectiveness values("BUG", "GHOST", 0.5);
insert into Effectiveness values("BUG", "DRAGON", 1);
insert into Effectiveness values("BUG", "DARK", 2);
insert into Effectiveness values("BUG", "STEEL", 0.5);
insert into Effectiveness values("BUG", "FAIRY", 0.5);

/*ROCK*/
insert into Effectiveness values("ROCK", "NORMAL", 1);
insert into Effectiveness values("ROCK", "FIRE", 2);
insert into Effectiveness values("ROCK", "WATER", 1);
insert into Effectiveness values("ROCK", "ELECTRIC", 1);
insert into Effectiveness values("ROCK", "GRASS", 1);
insert into Effectiveness values("ROCK", "ICE", 2);
insert into Effectiveness values("ROCK", "FIGHTING", 0.5);
insert into Effectiveness values("ROCK", "POISON", 1);
insert into Effectiveness values("ROCK", "GROUND", 0.5);
insert into Effectiveness values("ROCK", "FLYING", 2);
insert into Effectiveness values("ROCK", "PSYCHIC", 1);
insert into Effectiveness values("ROCK", "BUG", 2);
insert into Effectiveness values("ROCK", "ROCK", 1);
insert into Effectiveness values("ROCK", "GHOST", 1);
insert into Effectiveness values("ROCK", "DRAGON", 1);
insert into Effectiveness values("ROCK", "DARK", 1);
insert into Effectiveness values("ROCK", "STEEL", 0.5);
insert into Effectiveness values("ROCK", "FAIRY", 1);

/*GHOST*/
insert into Effectiveness values("GHOST", "NORMAL", 0);
insert into Effectiveness values("GHOST", "FIRE", 1);
insert into Effectiveness values("GHOST", "WATER", 1);
insert into Effectiveness values("GHOST", "ELECTRIC", 1);
insert into Effectiveness values("GHOST", "GRASS", 1);
insert into Effectiveness values("GHOST", "ICE", 1);
insert into Effectiveness values("GHOST", "FIGHTING", 1);
insert into Effectiveness values("GHOST", "POISON", 1);
insert into Effectiveness values("GHOST", "GROUND", 1);
insert into Effectiveness values("GHOST", "FLYING", 1);
insert into Effectiveness values("GHOST", "PSYCHIC", 2);
insert into Effectiveness values("GHOST", "BUG", 1);
insert into Effectiveness values("GHOST", "ROCK", 1);
insert into Effectiveness values("GHOST", "GHOST", 2);
insert into Effectiveness values("GHOST", "DRAGON", 1);
insert into Effectiveness values("GHOST", "DARK", 0.5);
insert into Effectiveness values("GHOST", "STEEL", 1);
insert into Effectiveness values("GHOST", "FAIRY", 1);

/*DRAGON*/
insert into Effectiveness values("DRAGON", "NORMAL", 1);
insert into Effectiveness values("DRAGON", "FIRE", 1);
insert into Effectiveness values("DRAGON", "WATER", 1);
insert into Effectiveness values("DRAGON", "ELECTRIC", 1);
insert into Effectiveness values("DRAGON", "GRASS", 1);
insert into Effectiveness values("DRAGON", "ICE", 1);
insert into Effectiveness values("DRAGON", "FIGHTING", 1);
insert into Effectiveness values("DRAGON", "POISON", 1);
insert into Effectiveness values("DRAGON", "GROUND", 1);
insert into Effectiveness values("DRAGON", "FLYING", 1);
insert into Effectiveness values("DRAGON", "PSYCHIC", 1);
insert into Effectiveness values("DRAGON", "BUG", 1);
insert into Effectiveness values("DRAGON", "ROCK", 1);
insert into Effectiveness values("DRAGON", "GHOST", 1);
insert into Effectiveness values("DRAGON", "DRAGON", 2);
insert into Effectiveness values("DRAGON", "DARK", 1);
insert into Effectiveness values("DRAGON", "STEEL", 0.5);
insert into Effectiveness values("DRAGON", "FAIRY", 0);

/*DARK*/
insert into Effectiveness values("DARK", "NORMAL", 1);
insert into Effectiveness values("DARK", "FIRE", 1);
insert into Effectiveness values("DARK", "WATER", 1);
insert into Effectiveness values("DARK", "ELECTRIC", 1);
insert into Effectiveness values("DARK", "GRASS", 1);
insert into Effectiveness values("DARK", "ICE", 1);
insert into Effectiveness values("DARK", "FIGHTING", 0.5);
insert into Effectiveness values("DARK", "POISON", 1);
insert into Effectiveness values("DARK", "GROUND", 1);
insert into Effectiveness values("DARK", "FLYING", 1);
insert into Effectiveness values("DARK", "PSYCHIC", 2);
insert into Effectiveness values("DARK", "BUG", 1);
insert into Effectiveness values("DARK", "ROCK", 1);
insert into Effectiveness values("DARK", "GHOST", 2);
insert into Effectiveness values("DARK", "DRAGON", 1);
insert into Effectiveness values("DARK", "DARK", 0.5);
insert into Effectiveness values("DARK", "STEEL", 1);
insert into Effectiveness values("DARK", "FAIRY", 0.5);

/*STEEL*/
insert into Effectiveness values("STEEL", "NORMAL", 1);
insert into Effectiveness values("STEEL", "FIRE", 0.5);
insert into Effectiveness values("STEEL", "WATER", 0.5);
insert into Effectiveness values("STEEL", "ELECTRIC", 0.5);
insert into Effectiveness values("STEEL", "GRASS", 1);
insert into Effectiveness values("STEEL", "ICE", 2);
insert into Effectiveness values("STEEL", "FIGHTING", 1);
insert into Effectiveness values("STEEL", "POISON", 1);
insert into Effectiveness values("STEEL", "GROUND", 1);
insert into Effectiveness values("STEEL", "FLYING", 1);
insert into Effectiveness values("STEEL", "PSYCHIC", 1);
insert into Effectiveness values("STEEL", "BUG", 1);
insert into Effectiveness values("STEEL", "ROCK", 2);
insert into Effectiveness values("STEEL", "GHOST", 1);
insert into Effectiveness values("STEEL", "DRAGON", 1);
insert into Effectiveness values("STEEL", "DARK", 1);
insert into Effectiveness values("STEEL", "STEEL", 0.5);
insert into Effectiveness values("STEEL", "FAIRY", 2);

/*FAIRY*/
insert into Effectiveness values("FAIRY", "NORMAL", 1);
insert into Effectiveness values("FAIRY", "FIRE", 0.5);
insert into Effectiveness values("FAIRY", "WATER", 1);
insert into Effectiveness values("FAIRY", "ELECTRIC", 1);
insert into Effectiveness values("FAIRY", "GRASS", 1);
insert into Effectiveness values("FAIRY", "ICE", 1);
insert into Effectiveness values("FAIRY", "FIGHTING", 2);
insert into Effectiveness values("FAIRY", "POISON", 0.5);
insert into Effectiveness values("FAIRY", "GROUND", 1);
insert into Effectiveness values("FAIRY", "FLYING", 1);
insert into Effectiveness values("FAIRY", "PSYCHIC", 1);
insert into Effectiveness values("FAIRY", "BUG", 1);
insert into Effectiveness values("FAIRY", "ROCK", 1);
insert into Effectiveness values("FAIRY", "GHOST", 1);
insert into Effectiveness values("FAIRY", "DRAGON", 2);
insert into Effectiveness values("FAIRY", "DARK", 2);
insert into Effectiveness values("FAIRY", "STEEL", 0.5);
insert into Effectiveness values("FAIRY", "FAIRY", 1);